config/routes.rb
Houseaccounts::Application.routes.draw do
  get "pages/home"
  resources :groups do
    collection do 
      post :add_new_group, :join_new_group
      get :join, :add
    end
  end
  resources :members do
    resources :payments
    member do
      post :send_email
    end
  end
  resources :users do 
    collection do 
      post :validate, :send_password_update_link, :handle_password_reset
    end
  end
  
  match 'forgotten_password' => 'users#forgotten_password', :as => :forgotten_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signin' => 'users#signin', :as => :signin
  match 'register' => 'users#new', :as => :register
  match '/signout' => 'users#signout', :as => :signout
  match '/' => 'pages#home', :as => :home
end

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessor :member_name, :current_user_id
  has_many :members
  has_many :users, :through => :members
  has_many :payments, :through => :members
  
  before_create :generate_group_token
  after_create :assign_member_on_create
  
  validates_presence_of :name, :on => :create
  validates_presence_of :current_user_id, :on => :create
  validates_presence_of :member_name, :on => :create
  
  def get_member(user)
    members.select {|member| member.user == user}.first
  end
  
  def generate_group_token(length=8)
    alphanumerics = ('a'..'z').to_a.concat(('A'..'Z').to_a.concat(('0'..'9').to_a))
    unless Group.find_by_group_token(alphanumerics)
      self.group_token = alphanumerics.sort_by{rand}.to_s[0..length]
    else
      generate_group_token
    end
  end
    
  def assign_member_on_create
    member = Member.create(:name => member_name, :group_id => id, :user_id => current_user_id)
    self.owner_id = member.id
  end
  
  def add_member(member_name, user_id)
    Member.create(:name => member_name, :group_id => id, :user_id => user_id)
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    
  end

  def edit
    @group = Group.find(params[:id])
    check_user_access(@group)
  end

  def show
    @group = Group.find(params[:id])
    check_user_access(@group)
  end

  def index
  end
  
  def join
    @user = User.find(params[:user_id])
  end
  
  def add
    @user = User.find(params[:user_id])
  end
  
  def join_new_group
    group = Group.find_by_group_token(params[:group_token])    
    group.add_member(params[:member_name], current_user.id)
    redirect_to group_path(group)
  end
  
  def add_new_group
    group = Group.new(params[:group])
    if group.save
      redirect_to group
    else
      flash[:error] = "Group did not create"
      redirect_to user_path(current_user)
    end
  end
  
end

app/helpers/groups_helper.rb
module GroupsHelper
  
  def home_top_nav_link(user)
    if request[:controller] == 'users' && request[:action] == 'show'
      link_to 'My Groups', user_path(user), :class => 'selected'
    else
      link_to 'My Groups', user_path(user)
    end
  end
  
  def group_top_nav_link(group)
    if (request[:controller] == 'groups' && params[:id].to_i == group.id) || (request[:controller] == 'members' && Member.find(params[:id].to_i).group.id == group.id)
      link_to group.name.titleize, group_path(group), :class => 'selected'
    else
      link_to group.name.titleize, group_path(group)
    end
  end
  
  def group_members(group, &block)
    if group.members.size == 1
      content_tag(:div, "You are the only member in this group", :class => 'subsection')
    else
      content_tag(:div, nil, &block)
    end
  end

end

app/views/groups/add.html.erb
<div class="section">
	<h2>Create new group</h2>
	<div class="subsection">
		<%= form_tag add_new_group_groups_path do %>	
			<%= hidden_field_tag 'group[current_user_id]', current_user.id %>
			<div class="field">
				<div>
				<%= label_tag 'Group Name' %>	
				</div>
				<div>
				<%= text_field_tag 'group[name]', nil, :placeholder => 'Choose a name for this group' %>
				</div>		
			</div>
			<div class="field">
				<div>
				<%= label_tag 'Your name in this group' %>	
				</div>
				<div>
				<%= text_field_tag 'group[member_name]', @user.name %>
				</div>
			</div>
			<div class="confirm_button" id="create_new_group_button">
			<%= submit_tag 'Create group' %>
			</div>
		<% end %>
	</div>
</div>

app/views/groups/edit.html.erb
<div class="section">
	<h2>Group Members</h2>
	<% @group.members.each do |member| %>
		<div class="subsection edit_group_member">
			<div class="subsection_buttons delete_button button">
				<%= link_to "Remove #{member.name.titleize}", member_path(member), :method => :delete, :confirm => "Are you sure you want to delete #{member.name.titleize} from this group?" %>
			</div>
			<div>
			<%= member.name.titleize %>
			<%= member_email_link(member) do %>
				<div class='member_email_link'>
					<%= link_to "Send email invitation to #{member.name.titleize}", nil, :id => "member_email_link_#{member.id}" %>
				</div>
				<div class="member_email_form" id="member_email_link_<%= member.id %>_form">
					<%= form_tag send_email_member_path(member) do %>
						<%= hidden_field_tag :group_id, params[:id] %>
						<%= hidden_field_tag :member_id, member.id %>
						<div>
							<%= label_tag 'email_address' %>
						</div>
						<div>
							<%= text_field_tag 'email_address' %>
						</div>
						<div>
							<%= submit_tag 'Send email', :class => 'confirm_button member_email_submit_button' %>
						</div>
					<% end %>
				</div>
			<% end %>
			</div>
		</div>
	<% end %>
</div>

<div class="section">
	<h2>Add new member</h2>
	<div class="subsection" id="add_new_member_panel">
		<div id="group_code">
			Code to join this group is <span class="strong"><%= @group.group_token %></span>
		</div>
		<%= form_tag members_path(@group) do %>
			<%= hidden_field_tag 'member[group_id]', @group.id %>
			<%= hidden_field_tag 'existing_member_id', @group.get_member(current_user).id %>
			<div class="field">
				<div>
				<%= label_tag :name %>
				</div>
				<div>
				<%= text_field_tag 'member[name]' %>
				</div>
			</div>
			<div class="field">
				<div>
				<%= label_tag :email %>
				</div>
				<div>
				<%= text_field_tag 'email' %>
				</div>
			</div>
			<%= submit_tag 'Add to Group' %>
		<% end %>
	</div>
</div>

app/views/groups/index.html.erb
<h1>Groups#index</h1>
<p>Find me in app/views/groups/index.html.erb</p>

app/views/groups/join.html.erb
<div class="section">
	<h2>Join new group</h2>
	<div class="subsection">
		<%= form_tag join_new_group_groups_path do %>	
			<div class="field">
				<div>
				<%= label_tag 'Group Token' %>	
				</div>
				<div>
					<%= text_field_tag :group_token, nil, :placeholder => "Enter your group token here" %>
				</div>
			</div>
			<div class="field">
				<div>
				<%= label_tag 'Your name in this group' %>	
				</div>
				<div>
				<%= text_field_tag :member_name, @user.name %>
				</div>
			</div>
			<div class="confirm_button" id="join_new_group_button">
			<%= submit_tag 'Join group' %>
			</div>
		<% end %>
	</div>
</div>

app/views/groups/new.html.erb
<h1>Groups#new</h1>
<p>Find me in app/views/groups/new.html.erb</p>

app/views/groups/show.html.erb
<div class="member_section">
	<div id="group_dropdown">
	  Overview
		<div id="group_dropdown_arrow">
			<%= image_tag 'backgrounds/group_dropdown_arrow.gif' %>
		</div>
	</div>
	<div id="group_dropdown_hidden">
		<% @group.members.each do |member| %>
			<%= link_to member.name.titleize, member_path(member) %>
		<% end %>
	</div>
</div>

<%= group_members(@group) do %>
	<% @group.members.each do |member| %>
		<div class="member_section">
			<h2><%= link_to member.name.titleize, member_path(member) %></h2>
			<div class="subsection">
				<div class="subsection_buttons">
					<div class="button confirm_button">
					<%= link_to 'View', member_path(member) %>
					</div>
				</div>
				<% member.other_members.each do |other_member| %>
					<div>
					<%= summary_for_member(member, other_member) %>
					</div>
				<% end %>
			</div>
		</div>
	<% end %>
<% end %>

<div id="group_edit_buttons">
	<div class="edit_button button" id="group_edit_group_button">
		<%= link_to 'Add or remove members', edit_group_path(@group) %>
	</div>
	<div class="delete_button button">
	<%= link_to 'Quit this group', group_path(@group) %>
	</div>
</div>