config/routes.rb
Houseaccounts::Application.routes.draw do
  get "pages/home"
  resources :groups do
    collection do 
      post :add_new_group, :join_new_group
      get :join, :add
    end
  end
  resources :members do
    resources :payments
    member do
      post :send_email
    end
  end
  resources :users do 
    collection do 
      post :validate, :send_password_update_link, :handle_password_reset
    end
  end
  
  match 'forgotten_password' => 'users#forgotten_password', :as => :forgotten_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signin' => 'users#signin', :as => :signin
  match 'register' => 'users#new', :as => :register
  match '/signout' => 'users#signout', :as => :signout
  match '/' => 'pages#home', :as => :home
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :members
  has_many :groups, :through => :members
  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation, :status, :site_id
  
  EmailRegex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  
  validates_format_of	:email, :with => EmailRegex
  validates_uniqueness_of :email, :case_sensitive => false
  validates_confirmation_of :password
  
  validates_presence_of :name, :on => :create
  validates_presence_of :password, :on => :create
  validates_length_of	:password, :within => 6..40, :on => :create
  
  before_save :encrypt_password
  before_create :generate_user_token
  
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end
  
  def self.authenticate(email, submitted_password)
    user = User.find_by_email(email)
     return nil if user.nil?
     return user if user.has_password?(submitted_password)
  end

  def remember_me!
    self.remember_token = encrypt("#{salt}--#{id}")
    save(:validate => false)
  end
  
  def assign_member(member_token)
    member = Member.find_by_member_token(member_token)
    member.update_attributes(:user_id => self.id)    
  end
  
  def generate_user_token(length=8)
    alphanumerics = ('a'..'z').to_a.concat(('A'..'Z').to_a.concat(('0'..'9').to_a))
    unless User.find_by_user_token(alphanumerics)
      self.user_token = alphanumerics.sort_by{rand}.to_s[0..length]
    else
      generate_user_token
    end
  end
  
  private
  
  def encrypt_password
    unless password.nil?
      self.salt = make_salt
      self.encrypted_password = encrypt(password)
    end
  end
  
  def encrypt(string) 
    secure_hash("#{salt}#{string}")
  end
  
  def make_salt
    secure_hash("#{Time.now.utc}#{password}")
  end
  
  def secure_hash(string)
    Digest::SHA2.hexdigest(string)
  end    
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :login_required, :except => [:edit, :show]
  include ApplicationHelper
  
  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
    check_user_access(@user)
  end

  def show
    @user = User.find(params[:id])
    check_user_access(@user)
  end
  
  def signin
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      @user.assign_member(params[:member_token]) if !params[:member_token].empty?
      set_user_cookie @user
      redirect_to @user
    else
      @user.errors.each do |error, message|
        flash_display(error, message)
      end
      #redirect_to new_user_path
      render 'new'
    end
  end
  
  def validate
    user = User.authenticate(params[:user][:email], params[:user][:password])
    if user.nil?
      flash[:success] = "Your email/password combination is invalid"
    redirect_to signin_path
    else
      set_user_cookie user
      redirect_to user
    end
  end
  
  def send_password_update_link
    user = User.find_by_email(params[:user][:email])
    if user
      UserMailer.forgotten_password_email(user).deliver
    else
      flash[:error] = "We couldn't find a user with that email address"
    end
  end
  
  def handle_password_reset
    user = User.find_by_user_token(params[:user][:user_token])
    if user.update_attributes(:password => params[:user][:password])
      flash[:success] = 'Your password has been updated'
      redirect_to user_path(user)
    else
      flash[:error] = 'There was an error. Your password has not been updated'
      redirect_to password_reset_path
    end
  end
  
  def signout
    sign_out
    redirect_to signin_path
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  def set_user_cookie(user)
    user.remember_me!
    cookies[:remember_token] = {:value => user.remember_token, :expires => 20.years.from_now.utc}
    self.current_user = user
  end
  
  def current_user=(user)
   @current_user = user
  end
  
  def current_user
    @current_user ||= user_from_remember_token
  end
  
  def user_from_remember_token
    remember_token = cookies[:remember_token]
    User.find_by_remember_token(remember_token) unless remember_token.nil?
  end
  
  def signed_in?
    !current_user.nil?
  end
  
  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end
  
  def user_group_summary(group, &block)
    if group.members.empty?
      content_tag(:div, "No other members have been added to this group")
    elsif group.payments.empty?
      content_tag(:div, "No payments have been added for this group")
    else
      content_tag(:div, nil, &block)
    end
  end
  
  def user_groups(user, &block)
    if user.groups.empty?
      content_tag(:div, "You haven't created or joined any groups yet!", :class => 'subsection')
    else
      content_tag(:div, nil, &block)
    end
  end
  
end

app/views/users/_register.html.erb
<h1>Register new account</h1>
<div>
	<%= form_for @user do |f| %> 
	
		<% if @user.errors.any? %>  
	  	<div id="errorExplanation">  
		    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>  
		    <ul>  
		    <% @user.errors.full_messages.each do |msg| %>  
		      <li><%= msg %></li>  
		    <% end %>  
		    </ul>  
		  </div>  
	  <% end %>
	
		<div class="field">
			<%= f.label :name %><br />
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %><br /> 
			<%= f.password_field :password %>
		</div> 
		<div class="field">
			<%= f.label :password_confirmation %><br /> 
			<%= f.password_field :password_confirmation %>
		</div>
		<div class="update_button">
			<%= f.submit "Register" %> 
		</div>
		<% end %> 
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/forgotten_password.html.erb
<h1>Forgotten Password</h1>
<div>
	<%= form_for(:user, :url => send_password_update_link_users_path) do |f| %> 
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
		<div class="update_button">
			<%= f.submit "Send password reset" %> 
		</div>
		<% end %> 
</div>

app/views/users/new.html.erb
<h1>Register</h1>
<div>
	<%= form_for @user do |f| %> 
		<%= hidden_field_tag 'member_token', params[:member_token] %>
	
		<div class="field">
			<%= f.label :name %><br />
			<%= f.text_field :name %>
		</div>
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %><br /> 
			<%= f.password_field :password %>
		</div> 
		<div class="field">
			<%= f.label :password_confirmation %><br /> 
			<%= f.password_field :password_confirmation %>
		</div>
		<div class="update_button">
			<%= f.submit "Register" %> 
		</div>
		<% end %> 
</div>

app/views/users/password_reset.html.erb
<h1>Password reset</h1>
<div>
	<%= form_for(:user, :url => handle_password_reset_users_path) do |f| %> 
		<%= f.hidden_field :user_token, :value => params[:user_token] %>
		<div class="field">
			<%= f.label :password %><br />
			<%= f.password_field :password %>
		</div>
		<div class="field">
			<%= f.label :password_confirmation %><br />
			<%= f.password_field :password_confirmation %>
		</div>
		<div class="update_button">
			<%= f.submit "Send password reset" %> 
		</div>
		<% end %> 
</div>

app/views/users/show.html.erb
<div class="section">
	<%= user_groups(@user) do %>
		<% @user.groups.each do |group| %>
			<div class="group">
				<h2><%= link_to group.name, group_path(group) %></h2>
				<div class="subsection users_subsection">
					<div class="subsection_buttons">
						<div class="button confirm_button">
						<%= link_to 'New payment', new_member_payment_path(group.get_member(@user)) %>
						</div>
					</div>
					<%= user_group_summary(group) do %>
						<% member = group.get_member(@user) %>
						<% member.other_members.each do |other_member| %>
							<div class="member_summary">
								<%= summary_for_member(member, other_member) %>
							</div>
						<% end %>
					<% end %>
				</div>
			</div>
		<% end %>
	<% end %>
</div>

<div id="add_group_buttons">
	<div class="edit_button button" id="join_group_button">
		<%= link_to 'Join group', join_groups_path(:user_id => @user.id) %>
	</div>
	<div class="confirm_button button">
	<%= link_to 'Create new group', add_groups_path(:user_id => @user.id) %>
	</div>
</div>

app/views/users/signin.html.erb
<h1>Sign in</h1>
<div>
	<%= form_for(:user, :url => validate_users_path) do |f| %> 
		<div class="field">
			<%= f.label :email %><br />
			<%= f.text_field :email %>
		</div>
		<div class="field">
			<%= f.label :password %><br /> 
			<%= f.password_field :password %>
		</div> 
		<div class="update_button">
			<%= f.submit "Sign in" %> 
		</div>
		<% end %> 
</div>
<div class="add_new" id="new_user_signup">
<%= link_to "Register", new_user_path %>
</div>
<div id="forgotten_password_link">
<%= link_to "Forgotten password?", forgotten_password_path %>
</div>