config/routes.rb
Houseaccounts::Application.routes.draw do
  get "pages/home"
  resources :groups do
    collection do 
      post :add_new_group, :join_new_group
      get :join, :add
    end
  end
  resources :members do
    resources :payments
    member do
      post :send_email
    end
  end
  resources :users do 
    collection do 
      post :validate, :send_password_update_link, :handle_password_reset
    end
  end
  
  match 'forgotten_password' => 'users#forgotten_password', :as => :forgotten_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signin' => 'users#signin', :as => :signin
  match 'register' => 'users#new', :as => :register
  match '/signout' => 'users#signout', :as => :signout
  match '/' => 'pages#home', :as => :home
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  belongs_to :member
  has_and_belongs_to_many :liable_members, :class_name => 'Member', :association_foreign_key => 'member_id', :join_table => 'payments_liable_members'
  #has_many :liable_members
  #has_many :members, :through => :liable_members
  
  attr_accessor :liable_member_ids

  validates_presence_of :amount
  validates_presence_of :member_id
  validates_presence_of :description
  validates_presence_of :liable_member_ids
  
  before_save :set_payment_details
  before_update :update_payment_details
  
  def set_payment_details
    self.liable_member_ids.each do |member_id|
      add_member_to_payment(member_id)
    end
  end
  
  def update_payment_details
    self.liable_members.clear
    set_payment_details
  end
  
  def add_member_to_payment(member_id)
    member = Member.find(member_id.to_i)
    liable_members << member
  end
  
  def spend_per_liable_member
    BigDecimal(amount) / liable_members.size
  end
  
  def amount_parse=(amount)
    if amount.include?(".")
      self.amount = amount.gsub(".", "")
    else
      self.amount = BigDecimal("#{amount}") * BigDecimal('100')
    end
  end
  
  def amount_parse
    self.amount
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  #layout 'blank'
  def create
    member = Member.find(params[:payment][:member_id])
    @payment = Payment.new(params[:payment])
    
    if @payment.save
      redirect_to member_path(member)
    else
      @payment.errors.each do |error, message|
        flash_display(error, message)
      end
      redirect_to member_path(member)
    end
  end
  
  def update
    member = Member.find(params[:payment][:member_id])
    @payment = Payment.find(params[:id])
    @payment.update_attributes(params[:payment])
    if @payment.save
      redirect_to member_path(member)
    else
      @payment.errors.each do |error, message|
        flash_display(error, message)
      end
      redirect_to member_path(member)
    end
  end
  
  def new
    @member = Member.find(params[:member_id])
    @payment = @member.payments.build
    @heading = 'New Payment'
  end
  
  def edit
    @member = Member.find(params[:member_id])
    @payment = Payment.find(params[:id])
    @heading = 'Edit Payment'    
  end
  
  def destroy
    member = Member.find(params[:member_id])
    payment = Payment.find(params[:id])
    payment.liable_members.clear
    payment.destroy
    redirect_to member_path(member)
  end
  
end

app/views/payments/_form.html.erb
<%= content_for :head do %>
<%= javascript_include_tag 'datepicker' %>
<%= stylesheet_link_tag 'cupertino/jquery-ui.css' %>
<script type="text/javascript">
	$(function() {
		$("#datepicker").datepicker({dateFormat: 'DD d MM yy', firstDay: 1});
	});
</script>
<% end %>

<h1><%= @heading %></h1>
<%= form_for [@member, @payment] do |f| -%>
	<%= f.hidden_field :member_id, :value => @member.id %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<div class="field">
		<div>
			<%= f.label :description %>
		</div>
		<div>
			<%= f.text_field :description %>
		</div>
	</div>
	<div class="field">
		<div>
			<%= f.label :amount %>
		</div>
		<div id="amount_field">
			<%= f.text_field :amount_parse, :value => display_price_for_form(@payment.amount) %>
			<div id="pound_sign">&pound;</div>
		</div>
	</div>
	<div class="field">
		<div>
			<%= f.label :date %>
		</div>
		<div>
			<%= f.text_field :date, :value => (l (@payment.date ||= Date.today), :format => :long), :id => 'datepicker' %>
		</div>
	</div>
	<div class="field" id="group_field">
		<div>
			<%= f.label 'Who owes?' %>
		</div>
		<div id="quick_payment_groups">
			<% @member.group.members.each do |member| %>
				<div class="quick_payment_liable_member">
					<div class="quick_payment_liable_member_input">
						<%= check_box_tag "payment[liable_member_ids][]", member.id, @payment.liable_members.include?(member), :id => "liable_member_#{member.name.parameterize}" %>
					</div>
					<div class="quick_payment_liable_member_name">
						<%= label_tag "liable_member_#{member.name.parameterize}", member.name %>
					</div>
				</div>
			<% end %>
		</div>
		
	</div>
	<div id="payment_submit">
		<%= f.submit 'Save payment' %>
	</div>
  
<% end -%>

app/views/payments/_form_including_js.html.erb
<%= content_for :head do %>
<%= javascript_include_tag 'datepicker' %>
<%= stylesheet_link_tag 'cupertino/jquery-ui.css' %>
<script type="text/javascript">
	$(function() {
		$("#datepicker").datepicker({dateFormat: 'DD d MM yy', firstDay: 1});
	});
</script>
<% end %>

<h1>Quick payment</h1>
<%= form_for @payment, :url => member_payments_path(@member) do |f| -%>
<div id="group_select">
	<div>
		<%= f.select :group_id, options_from_collection_for_select(current_user.groups, 'id', 'name', params[:group_id]) %>
	</div>
</div>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<div class="field">
		<div>
			<%= f.label :amount %>
		</div>
		<div id="amount_field">
			<%= f.text_field :amount_parse %>
			<div id="pound_sign">&pound;</div>
		</div>
	</div>
	<div class="field">
		<div>
			<%= f.label :description %>
		</div>
		<div>
			<%= f.text_field :description %>
		</div>
	</div>
	<div class="field">
		<div>
			<%= f.label :date %>
		</div>
		<div>
			<%= f.text_field :date, :value => (l Date.today, :format => :long), :id => 'datepicker' %>
		</div>
	</div>
	<div class="field" id="group_field">
		<div>
			<%= f.label 'Who owes?' %>
		</div>
		<div id="quick_payment_groups">
		</div>
		</div>
		
	</div>
	<div id="payment_submit">
		<%= f.submit 'Save payment' %>
	</div>
  
<% end -%>

<div id="quick_payment_groups_hidden">
<% current_user.groups.each do |group| %>
	<div class="quick_payment_group" id="quick_payment_group_<%= group.id %>">
	<%= hidden_field_tag 'payment[member_id]', group.get_member(current_user).id %>
	<% group.members.each do |member| %>
		<div class="quick_payment_liable_member">
			<div class="quick_payment_liable_member_input">
				<%= check_box_tag "payment[liable_member_ids][]", member.id %>
			</div>
			<div class="quick_payment_liable_member_name">
				<%= label_tag member.name %>
			</div>
		</div>
	<% end %>
	</div>
<% end %>
</div>


<script>
	<% preloaded_group =  params[:group_id] ? params[:group_id] : current_user.groups.first.id %>
	$('#quick_payment_groups').html($('#quick_payment_group_' + <%= preloaded_group %>).clone());

	$('#payment_group_id').change(function() {
		var group_id = $(this).val();
	  $('#quick_payment_groups').html($('#quick_payment_group_' + group_id).clone());
	});
</script>

app/views/payments/_lightbox.html.erb
<div class="hidden">
	<div id="quick_payment">
		<h1>Quick payment</h1>
		<% form_for @payment do |f| -%>
			<%= f.hidden_field :user_id, :value => current_user.id %>
			<%= f.hidden_field :member_id, :value => params[:id] %>
			<div class="field">
				<div>
					<%= f.label :amount %>
				</div>
				<div>
					<%= f.text_field :amount %>
				</div>
			</div>
			<div class="field">
				<div>
					<%= f.label :description %>
				</div>
				<div>
					<%= f.text_field :description %>
				</div>
			</div>
			<div class="field">
				<div>
					<%= f.label :date %>
				</div>
				<div>
					<%= f.text_field :date, :value => Date.today %>
				</div>
			</div>
			<div class="field">
				<div>
					<%= f.label :paid_by %>
				</div>
				<div>
					<%= f.select :member_id, options_from_collection_for_select(@group.members, 'id', 'name', params[:member_id]) %>
				</div>
			</div>
			<div class="field">
				<% @group.members.each do |member| %>
					<div>
					<%= label_tag member.name %>
					<%= check_box_tag "payment[liable_member_ids][]", member.id %>
					</div>
				<% end %>
			</div>
			<div>
				<%= f.submit 'Add payment' %>
			</div>

		<% end -%>
	</div>
</div>

app/views/payments/edit.html.erb
<div id="edit_payment_form">
	<%= render 'form' %>
	<div class='button delete_button' id='edit_payment_delete_button'>
		<%= link_to 'Delete payment', member_payment_path(@member, @payment), :method => :delete %>
	</div>
</div>

app/views/payments/new.html.erb
<%= render 'form' %>