config/routes.rb
Houseaccounts::Application.routes.draw do
  get "pages/home"
  resources :groups do
    collection do 
      post :add_new_group, :join_new_group
      get :join, :add
    end
  end
  resources :members do
    resources :payments
    member do
      post :send_email
    end
  end
  resources :users do 
    collection do 
      post :validate, :send_password_update_link, :handle_password_reset
    end
  end
  
  match 'forgotten_password' => 'users#forgotten_password', :as => :forgotten_password
  match 'password_reset' => 'users#password_reset', :as => :password_reset
  match 'signin' => 'users#signin', :as => :signin
  match 'register' => 'users#new', :as => :register
  match '/signout' => 'users#signout', :as => :signout
  match '/' => 'pages#home', :as => :home
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :payments
  has_and_belongs_to_many :liable_payments, :class_name => 'Payment', :association_foreign_key => 'payment_id', :join_table => 'payments_liable_members'
  #has_many :payments
  belongs_to :user
  belongs_to :group
  
  validates_uniqueness_of :name, :case_sensitive => false, :scope => :group_id
  
  before_create :generate_member_token
  
  def other_members
    group.members.select {|member| member != self}
  end
  
  def spend_for_member(member)
    total_payments = payments_for_member(member).map(&:spend_per_liable_member)
    BigDecimal("#{total_payments.inject {|a,b| a + b }}")
  end
  
  def payments_for_member(member)
    payments.select {|payment| payment.liable_members.include?(member)}
  end
  
  def balance_compared_to(member)
    spend_for_member(member) - member.spend_for_member(self)
  end
  
  def generate_member_token(length=8)
    alphanumerics = ('a'..'z').to_a.concat(('A'..'Z').to_a.concat(('0'..'9').to_a))
    unless Member.find_by_member_token(alphanumerics)
      self.member_token = alphanumerics.sort_by{rand}.to_s[0..length]
    else
      generate_member_token
    end
  end
  
  def liability_for_payment(payment)
    owes_for_payment?(payment) ? payment.spend_per_liable_member : nil
  end
  
  def owes_for_payment?(payment)
    payment.liable_members.include?(self)
  end
  
  def last_10_payments
    payments.order('created_at DESC').first(10)
  end
  
  def all_payments
    payments.order('created_at DESC')
  end
  
  def overall_balance
    total = other_members.inject(0) do |total, other_member|
      total + balance_compared_to(other_member)
    end    
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  include ApplicationHelper
  def new
  end

  def edit
    @member = Member.find(params[:id])
    check_user_access(@member)
  end

  def show
    @member = Member.find(params[:id])
    @group = @member.group
    @payment = Payment.new
    check_user_access(@member)
  end
  
  def create
    @member = Member.new(params[:member])
    @existing_member = Member.find(params[:existing_member_id])
    if @member.save
      if email_valid?(params[:email])
        UserMailer.welcome_email(@member, @existing_member, params[:email]).deliver
      end
      redirect_to member_path(@member)
    else
      redirect_to user_path(current_user)
    end
  end
  
  def destroy
    member = Member.find(params[:id])
    if member.overall_balance == 0
      member.destroy
    else
      flash[:error] = "#{member.name.titleize} still has an unsettled balance!"
    end
    redirect_to group_path(member.group)
  end
  
  def send_email
    group = Group.find(params[:group_id])
    existing_member = group.get_member(current_user)
    member = Member.find(params[:member_id])
    email = params[:email_address]
    if email_valid?(params[:email_address])
      UserMailer.welcome_email(member, existing_member, email).deliver
      flash[:success] = "A welcome email has been sent to #{member.name.titleize}!"
    else
      flash[:error] = "The email address has not been recognised"
    end
    redirect_to edit_group_path(group)
  end

end

app/helpers/members_helper.rb
module MembersHelper
  def summary_for_member(member, other_member)
    member.user ? member_is_current_user = (member.user.id == current_user.id) : nil
    balance = member.balance_compared_to(other_member)
    if balance > 0
      summary = member_is_current_user ? "#{other_member.name} owes me #{display_balance(balance)}" : "is owed #{display_balance(balance)} by #{other_member.name}"
      content_tag(:div, summary, :class => 'member_summary owed')
    elsif balance < 0
      summary = member_is_current_user ? "I owe #{other_member.name} #{display_balance(balance.abs)}" : "owes #{other_member.name} #{display_balance(balance.abs)}"
      content_tag(:div, summary, :class => 'member_summary owes')
    else
      summary = member_is_current_user ? "I am square with #{other_member.name}" : "is square with #{other_member.name}"
      content_tag(:div, summary, :class => 'member_summary square')
    end
  end
  
  def last_10_payments(member, &block)
    member.user ? member_is_current_user = (member.user.id == current_user.id) : nil
    statement = member_is_current_user ? "You have not made any payments yet" : "#{member.name.titleize} has not made any payments yet"
    if member.payments.empty?
      content_tag(:div, statement, :class => 'subsection')
    else
      @collection =  params[:all_payments] ? member.all_payments : member.last_10_payments
      content_tag(:div, nil, &block)
    end
  end
  
  def member_email_link(member, &block)
    if member.user
      return
    else
      content_tag(:div, nil, &block)
    end
  end
  
  def all_payments_link(member, &block)
    if member.payments.size > 10
      content_tag(:div, nil, &block)
    end
  end
      
end

app/views/members/edit.html.erb
<h1>Members#edit</h1>
<p>Find me in app/views/members/edit.html.erb</p>

app/views/members/new.html.erb
<h1>Members#new</h1>
<p>Find me in app/views/members/new.html.erb</p>

app/views/members/show.html.erb
<%= content_for :head do %>
	<link rel="prerender" href="<%= new_member_payment_path(@member) %>">
<% end %>

<% if @member.errors.any? %>  
	<div id="errorExplanation">  
    <ul>
    <% @member.errors.full_messages.each do |msg| %>  
      <li><%= msg %></li>  
    <% end %>  
    </ul>  
  </div>  
<% end %>

<div class="member_section">
	<div id="group_dropdown">
	  <%= @member.name.titleize %>
		<div id="group_dropdown_arrow">
			<%= image_tag 'backgrounds/group_dropdown_arrow.gif' %>
		</div>
	</div>
	<div id="group_dropdown_hidden">
		<%= link_to 'Overview', group_path(@group) %>
		<% @group.members.each do |member| %>
			<%= link_to member.name.titleize, member_path(member) %>
		<% end %>
	</div>
</div>

<div class="section">
	<h2><%= "#{@member.name.titleize}'s Summary" %></h2>
	<div class="subsection">
		<div class="subsection_buttons button confirm_button">
			<%= link_to 'New payment', new_member_payment_path(@member) %>
		</div>
	<% @member.other_members.each do |other_member| %>
		<%= summary_for_member(@member, other_member) %>
	<% end %>
	</div>
</div>


<%= last_10_payments(@member) do %>
<div class="section" id="member_last_10_payments">
	<%= all_payments_link(@member) do %>
		<div id='all_payments_link'>
			<%= link_to 'Show all payments', member_path(@member, :all_payments => true)%>
		</div>
	<% end %>
	<h2>Last 10 payments</h2>
	<div class="subsection">
		<table>
			<tr>
				<th></th>
				<th></th>
				<% @member.group.members.each do |member| %>
					<th><%= member.name.titleize %></th>
				<% end %>
				<th></th>
			</tr>
			
			<% @collection.each do |payment| %>
				<tr>
					<td class="payment_amount"><%= display_balance(payment.amount) %></td>
					<td  class="payment_description">
						<div>
						<%= payment.description %>
						</div>
						<div class="payment_date">
							<%= l payment.date, :format => :short %>
						</div>
					</td>
					<% @member.group.members.each do |member| %>
						<td class="liable_member <%= member.owes_for_payment?(payment) %>"><%= display_balance(member.liability_for_payment(payment)) %></td>
					<% end %>
					<td>
					<%= link_to 'Edit', edit_member_payment_path(@member, payment) %>
						</td>
				</tr>
			<% end %>
		</table>
	</div>
</div>
<% end %>